import type { IconType } from "react-icons";
import {
  SiAirtable,
  SiApollographql,
  SiContentful,
  SiDiscord,
  SiElevenlabs,
  SiFirebase,
  SiGhost,
  SiGithub,
  SiGitlab,
  SiGmail,
  SiGoogleanalytics,
  SiGooglecalendar,
  SiGoogledrive,
  SiGooglesheets,
  SiHubspot,
  SiInstagram,
  SiJira,
  SiLinear,
  SiMixpanel,
  SiNotion,
  SiOpenai,
  SiPaypal,
  SiPiped,
  SiQuickbooks,
  SiReplicate,
  SiSalesforce,
  SiShopify,
  SiSlack,
  SiStripe,
  SiSupabase,
  SiTelegram,
  SiTodoist,
  SiVercel,
  SiWebflow,
  SiWoocommerce,
  SiWordpress,
  SiX,
  SiYoutube,
} from "react-icons/si";
import { FaAws, FaLinkedin, FaMicrosoft } from "react-icons/fa";
import { PiMicrosoftOutlookLogo } from "react-icons/pi";
import { TbArrowsSplit, TbPlugConnected } from "react-icons/tb";

export const integrationIconMap: Record<string, IconType> = {
  SiGmail,
  SiSlack,
  SiDiscord,
  FaMicrosoft,
  PiMicrosoftOutlookLogo,
  SiTelegram,
  SiApollographql,
  SiHubspot,
  SiSalesforce,
  SiPiped,
  SiWordpress,
  SiWebflow,
  SiGhost,
  SiContentful,
  SiYoutube,
  SiX,
  FaLinkedin,
  SiInstagram,
  SiGooglesheets,
  SiGooglecalendar,
  SiGoogledrive,
  SiNotion,
  SiAirtable,
  SiTodoist,
  SiGithub,
  SiGitlab,
  SiJira,
  SiLinear,
  SiVercel,
  SiStripe,
  SiPaypal,
  SiQuickbooks,
  SiGoogleanalytics,
  SiMixpanel,
  SiSegment: TbArrowsSplit,
  SiAws: FaAws,
  SiSupabase,
  SiFirebase,
  SiShopify,
  SiWoocommerce,
  SiOpenai,
  SiReplicate,
  SiElevenlabs,
};

export function getIntegrationIcon(iconKey: string): IconType {
  return integrationIconMap[iconKey] ?? TbPlugConnected;
}
